POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Ghassen Faidi",
    "phone": "+216 12345678"
}
###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Ghassen Faidi"
}

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "phone": "+216 12345678"

}

###
POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "      ",
    "phone": "+216 12345678"

}