POST http://localhost:3001/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Ghassen Faidi",
    "number": "+216 12345678"
}
###
POST https://phonebook-1n1q.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "Ghassen Faidi"
}

###
POST https://phonebook-1n1q.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "",
    "number": "+216 12345678"

}

###
POST https://phonebook-1n1q.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
    "name": "      ",
    "number": "+216 12345678"

}